name: Ruff Lint and Format

on:
  pull_request:
    branches:
      - '*'

jobs:
   ruf-lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.4.1
        with:
          version: 1.8.4

      - name: Install dependencies using Poetry
        run: |
          poetry install

      - name: Run ruff lint
        uses: astral-sh/ruff-action@v3
