name: Ruff Lint and Format

on:
  pull_request:
    branches:
      - '*'

jobs:
  ruf-lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up UV
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies using UV
        run: |
          uv sync

      - name: Run ruff lint
        uses: astral-sh/ruff-action@v3
        run: |
          run ruff check

